##Length of 5' UTRs

##Downloaded from Biomart 17-05-2018. Mouse GRCm38.p6

library(readr)
library(ggplot2)
library(reshape2)

UTR_length <- read_csv("Mouse GRCm38.p6 Ensembl biomart 17-05-2018.txt")
UTR_length <- unique(UTR_length)

colnames(UTR_length) <- c("Gene_ID", "Transcript_ID", "UTR_start", "UTR_end", "Gene_name")

UTR_length <- UTR_length[!is.na(UTR_length$UTR_start),]
UTR_length <- UTR_length[!is.na(UTR_length$UTR_end),]

UTR_length$UTR_length <- (UTR_length$UTR_end-UTR_length$UTR_start) + 1


length(unique(UTR_length$Gene_name))  #each gene on average 4 5'UTR lengths

hist(log10(UTR_length$UTR_length))

##Removing greater than 500

UTR_length <- UTR_length[UTR_length$UTR_length < 500,]
UTR_length$Gene_name <- toupper(UTR_length$Gene_name)

hist(log10(UTR_length$UTR_length))

##Minimum of each gene

UTR_length_min <- aggregate(UTR_length ~ Gene_name, UTR_length, min)

hist(log10(UTR_length_min$UTR_length))

#CMB vs Ctrl
##Generated by "Limma analysis of resistant study.R"
limma_resistance_CMB <- read.table("Sig_genes_CM_Ct_poly_all.txt", sep="\t",
                                   header=TRUE)

limma_resistance_CMB_sig <- limma_resistance_CMB[limma_resistance_CMB$adj.P.Val < 0.05,]

limma_resistance_CMB_sig_up <- limma_resistance_CMB_sig[limma_resistance_CMB_sig$logFC >= log2(1.5),]
limma_resistance_CMB_sig_down <- limma_resistance_CMB_sig[limma_resistance_CMB_sig$logFC <= -log2(1.5),]
limma_resistance_CMB_sig_both <- limma_resistance_CMB_sig[abs(limma_resistance_CMB_sig$logFC) >= log2(1.5),]


UTR_length_min_CMB <- aggregate(UTR_length ~ Gene_name, UTR_length, min)

##Use only expressed genes
UTR_length_min_CMB <- UTR_length_min_CMB[UTR_length_min_CMB$Gene_name %in% toupper(limma_resistance_CMB$genes),]

UTR_length_min_CMB$Resistance <- "Not_different"

UTR_length_min_CMB$Resistance[UTR_length_min_CMB$Gene_name %in% toupper(limma_resistance_CMB_sig_up$genes)] <- "Up"
UTR_length_min_CMB$Resistance[UTR_length_min_CMB$Gene_name %in% toupper(limma_resistance_CMB_sig_down$genes)] <- "Down"

ggplot(subset(UTR_length_min_CMB, Resistance != "Not_different"), aes(x=Resistance, y = log10(UTR_length)))+
  geom_boxplot(aes(colour=Resistance))+
  scale_color_manual(values=c("forestgreen", "cornflowerblue"))+
  coord_flip()+
  theme_bw()

wilcox.test(UTR_length_min_CMB$UTR_length[UTR_length_min_CMB$Resistance == "Up"],
            UTR_length_min_CMB$UTR_length[UTR_length_min_CMB$Resistance == "Down"], alternative="less")


##CX vs. Ctrl
##Generated by "Limma analysis of resistant study.R"
limma_resistance_CX <- read.table("Sig_genes_CX_Ct_poly_all.txt", sep="\t",
                                  header=TRUE)

limma_resistance_CX_sig <- limma_resistance_CX[limma_resistance_CX$adj.P.Val < 0.05,]

limma_resistance_CX_sig_up <- limma_resistance_CX_sig[limma_resistance_CX_sig$logFC >= log2(1.5),]
limma_resistance_CX_sig_down <- limma_resistance_CX_sig[limma_resistance_CX_sig$logFC <= -log2(1.5),]
limma_resistance_CX_sig_both <- limma_resistance_CX_sig[abs(limma_resistance_CX_sig$logFC) >= log2(1.5),]


UTR_length_min_CX <- aggregate(UTR_length ~ Gene_name, UTR_length, min)

##Use only expressed genes
UTR_length_min_CX <- UTR_length_min_CX[UTR_length_min_CX$Gene_name %in% toupper(limma_resistance_CX$genes),]

UTR_length_min_CX$Resistance <- "Not_different"

UTR_length_min_CX$Resistance[UTR_length_min_CX$Gene_name %in% toupper(limma_resistance_CX_sig_up$genes)] <- "Up"
UTR_length_min_CX$Resistance[UTR_length_min_CX$Gene_name %in% toupper(limma_resistance_CX_sig_down$genes)] <- "Down"

ggplot(subset(UTR_length_min_CX, Resistance != "Not_different"), aes(x=Resistance, y = log10(UTR_length)))+
  geom_boxplot(aes(colour=Resistance))+
  scale_color_manual(values=c("forestgreen", "cornflowerblue"))+
  coord_flip()+
  theme_bw()

wilcox.test(UTR_length_min_CX$UTR_length[UTR_length_min_CX$Resistance == "Up"],
            UTR_length_min_CX$UTR_length[UTR_length_min_CX$Resistance == "Down"], alternative="less")
