#Read in libraries and functions

library(limma)
library(edgeR)
library(ggplot2)
library(ggrepel)

source("helper_functions.R")

##Generated by "Limma analysis of resistant study.R"
limma_results_CM_Ct <- read.table("Sig_genes_CM_Ct_poly_all.txt", sep="\t",
                                  header=TRUE)
limma_results_CX_Ct <- read.table("Sig_genes_CX_Ct_poly_all.txt", sep="\t",
                                  header=TRUE)

OX_genes <- c("Ndufv1","Ndufc2","Ndufb8","Ndufb5","Ndufa4","Ndufa5",
              "Ndufb2","Cyc1","Uqcrc1","Uqcrb","Cox4i1","Atp5a1","Atp5b","Atp5f1")

OX_CM_Ct <- limma_results_CM_Ct[match(OX_genes, limma_results_CM_Ct$genes),]
OX_CX_Ct <- limma_results_CX_Ct[match(OX_genes, limma_results_CX_Ct$genes),]
OX_df <- rbind(cbind(OX_CM_Ct, Comparison="CM_Ct"),
               cbind(OX_CX_Ct, Comparison="CX_Ct"))

print(plot_p_logFC(OX_df, OX_genes))
